name: flutter_news_clean_arch_full
description: "Clean Architecture + BLoC + get_it + Retrofit(Dio) + Hive"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # DI
  get_it: ^7.7.0

  # HTTP + Retrofit
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.9.0

  # Caching & utils
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.0.4
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  mockito: ^5.4.5

